
#application.yml : ?????? ?? ??? ???? ?? ??????? ???? ????

#?? application.properties ? ???, ??????? ??? ? properties? ???? ??? ?.

#???? ????????, ???? ????? ?????? ???.

#//???? ??? yml
#
#??? + f6?. ?? ? ????.

#??? ?????? ???? ? ?????????? ???? ????.?
# properties? ????? ? ??????. but ???  ??? ???? ???? ?? ?????. ? ????.??!



#1. ???????! ??
server:
  #?? ?? ?? ??????.
  prot: 8080
  servlet:
    #?????? ????????? ?? ??? ??? ???? ?? ?????????..
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  #  --mysql ohgirafffers ???????! -
  #ohgiraffers_db databbase ????,
  #ohgiraffers_db? ?? ??? ohgiraffers ??? ?????.
  #????????, ???????? ?????? ?????.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ohgiraffers_db?serverTimezone=Asia/Seoul
    username: ohgiraffers
    password: ohgiraffers
    #???? ???????.. ?????

    #??? jpa?????


    #???????? : jpa? ?????, ???? db?????
    #???? entity???? ????? -> ??? ?????? ??,?????????. ?..
    # jpa? post_id? ???? ??? ????? ?? ????????..

    #ddl-auto? ?? entity??? ???? ???-> show sql???? ???? ????? ???????,
    #- ddl-auto ???? ??????sql?? jpa? ???? ?? ? ???????.
    #ddl-auto?? create? ?????? ??? ??? ?????? (???)?????, ?????? ???. ?, ?????? ??? ???? ????.
    # 'create-drop' ? ??? ?????? ??? ??? ?????????? ??, ?? ???? ???.
    #???????, ???? ?????
    # 'update' : ?????? ??? ?????? ???? ?????.
    #-- ???? ????..--
    #??? ddl-auto? create-> update?  ?? ????. (??? ?????? ???) ??? ??!?..
    # ? ???? yml?? ?????.


#create -> update? ????..?  ddl-auto!
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hiberate.dialect.MySQL57Dialect
          #??????? ????? sql?? ??? ?????? ???. show_sql ???.
          show_sql: true




# ?????? ???? ?????! ?????.. ?????? ??????.. ?????- ???? ??? ?????!

